Repository devcareer/code-jammers-backend, pull requests merged in 2020-10, with the labels that each got.

#39 Fix: Fix some sign up credentials
  .codeclimate.yml
  .env.sample
  .github/workflows/node.js.yml
  package.json
  src/controllers/user.js
  src/database/config/config.js
  src/database/index.js
  src/models/User.js
  src/models/countries.js
  src/models/culture.js
  src/models/index.js
  src/tests/controllers/users/user-test-data.js
  src/tests/controllers/users/user-test.js
  src/utilities/util.js
  src/validation/userValidation.js
Labels: bug, hacktoberfest

#37 #174879632 Setup user account verification
  .env.sample
  .gitignore
  package.json
  src/config/config.js
  src/controllers/user.js
  src/database/migrations/20200903160620-create-user.js
  src/database/seeders/20200904133535-User.js
  src/models/User.js
  src/routes/userRoutes.js
  src/services/UserService/User.js
  src/tests/controllers/users/user-sign-in-test-data.js
  src/tests/controllers/users/user-sign-in-test.js
  src/tests/controllers/users/user-test-data.js
  src/tests/controllers/users/user-test.js
  src/tests/models/user.spec.js
  src/utilities/sendgrid.js
  src/validation/userValidation.js
Labels: hacktoberfest, review me

#36 #174879639 Build Api for admin to add a country
  .babelrc
  .codeclimate.yml
  .eslintrc.json
  .hound.yml
  package.json
  src/app.js
  src/controllers/country.js
  src/controllers/index.js
  src/controllers/user.js
  src/database/config/config.js
  src/database/config/passport.js
  src/database/migrations/20200903144113-create-countries.js
  src/database/seeders/20200904133535-User.js
  src/middlewares/authenticate.js
  src/middlewares/index.js
  src/models/countries.js
  src/routes/adminRoutes.js
  src/routes/index.js
  src/services/AdminServices/countryService.js
  src/services/UserService/User.js
  src/tests/controllers/admin/addCountry.test.js
  src/tests/controllers/admin/addcountry-data.js
  src/tests/controllers/users/user-sign-in-test-data.js
  src/tests/controllers/users/user-sign-in-test.js
  src/tests/controllers/users/user-test-data.js
  src/tests/controllers/users/user-test.js
  src/tests/index-test.js
  src/tests/index.js
  src/utilities/Jwt.js
  src/utilities/sendgrid.js
  src/utilities/util.js
  src/validation/countryValidation.js
  src/validation/index.js
  src/validation/userValidation.js
Labels: hacktoberfest, work-in-progress
