Repository devcareer/code-jammers-backend, pull requests merged in 2020-11, with the labels that each got.

#40 #175218188 Newsletter and subscription APIs
  .eslintrc.json
  package.json
  src/app.js
  src/controllers/index.js
  src/controllers/newsletter/newsletter.js
  src/controllers/newsletter/subscriber.js
  src/controllers/user/user.js
  src/database/index.js
  src/database/migrations/20200908133515-create-music.js
  src/database/migrations/20200914130656-create-newsletter.js
  src/database/migrations/20201015112042-create-subscriber.js
  src/database/migrations/20201015160026-create-newsletter-subscriber.js
  src/database/seeders/20200906160720-state.js
  src/database/seeders/20200907150538-Music.js
  src/database/seeders/20200914145035-newsletter.js
  src/database/seeders/20201015112608-subscriber.js
  src/database/seeders/20201015163227-newsletter_subscriber.js
  src/models/countries.js
  src/models/music.js
  src/models/newsletter.js
  src/models/newsletter_subscriber.js
  src/models/subscriber.js
  src/routes/index.js
  src/routes/newsletterRoute/newsletterRoutes.js
  src/routes/userRoute/userRoutes.js
  src/services/newsletterServices/newsletter.js
  src/services/newsletterServices/subsciber.js
  src/tests/controllers/newsletter/newsletter-test-data.js
  src/tests/controllers/newsletter/newsletter.test.js
  src/tests/index.js
  src/tests/models/music.spec.js
  src/tests/models/newsletter.spec.js
  src/utilities/sendgrid.js
  src/validation/newsletterValidation.js
  src/validation/userValidation.js
Labels: hacktoberfest, review me

#42 #175357378 Build CRUD API for tourist center
  .env.sample
  src/app.js
  src/controllers/country.js
  src/controllers/index.js
  src/controllers/touristCenter.js
  src/database/migrations/20200906143952-create-tourist-center.js
  src/models/touristCenter.js
  src/routes/countryRoutes.js
  src/routes/index.js
  src/routes/touristCenterRoutes.js
  src/services/AdminServices/touristCenterService.js
  src/tests/controllers/admin/addCountry.test.js
  src/tests/controllers/touristCenter/touristCenter-data.js
  src/tests/controllers/touristCenter/touristCenter.test.js
  src/tests/index.js
  src/tests/intergration/CountriesRoutes.spec.js
  src/tests/unit/controllers/CountriesController.spec.js
  src/utilities/util.js
  src/validation/touristCenterValidation.js
Labels: hacktoberfest, review me

#33 #174838707 A user should be able to reset their password [WIP]
  .eslintrc.json
  package.json
  src/.env.sample
  src/app.js
  src/controllers/index.js
  src/controllers/resetPasswordController.js
  src/models/profile.js
  src/routes/resetPasswordRoutes.js
  src/tests/controllers/resetPasswordTest/reset-test-data.js
  src/tests/controllers/resetPasswordTest/resetPasswordWithSinonTest.js
  src/tests/controllers/users/user-test-data.js
  src/tests/index.js
  src/utilities/hashPassword.js
  src/utilities/sendgrid.js
  src/utilities/signToken.js
Labels: hacktoberfest, review me

#41 #175355965 Build CRUD API for state
  src/app.js
  src/controllers/country.js
  src/controllers/state.js
  src/controllers/user/user.js
  src/database/migrations/20200906145335-create-state.js
  src/database/seeders/20200906160720-state.js
  src/models/state.js
  src/routes/stateRoutes.js
  src/services/AdminServices/stateService.js
  src/tests/controllers/admin/addState-data.js
  src/tests/controllers/admin/addState.test.js
  src/tests/controllers/states/state-data.js
  src/tests/controllers/states/state.test.js
  src/tests/controllers/touristCenter/touristCenter.test.js
  src/tests/index.js
  src/tests/unit/controllers/CountriesController.spec.js
  src/validation/stateValidation.js
Labels: hacktoberfest, review me

#58 Containerise the Know Africa web app using Docker
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  package.json
  src/.env.sample
  src/app.js
  src/database/config/config.js
  src/routes/foodRoute/foodRoutes.js
  src/utilities/hashPassword.js
Labels: review me

#56 #175537319 Build historical facts CRUD APIs
  src/app.js
  src/controllers/country/country.js
  src/controllers/historicalFacts/historicalFacts.js
  src/models/countries.js
  src/models/historicalfact.js
  src/routes/historicalFactsRoute/historicalFactsRoute.js
  src/routes/index.js
  src/routes/touristCenterRoute/touristCenterRoutes.js
  src/services/AdminServices/historicalFactsService.js
  src/tests/controllers/historicalFacts/historicalFacts.data.js
  src/tests/controllers/historicalFacts/historicalFacts.test.js
  src/tests/controllers/music/music.test.js
  src/tests/index.js
  src/tests/unit/controllers/CountriesController.spec.js
  src/validation/historicalFactsValidation.js
Labels: review me

#48 #175541724 Build CRUD API's for comment
  src/app.js
  src/controllers/commentController.js
  src/controllers/country/country.js
  src/controllers/index.js
  src/database/migrations/20200914124552-create-comment.js
  src/database/seeders/20200914145022-comment.js
  src/models/comment.js
  src/models/countries.js
  src/models/ethnicgroup.js
  src/models/food.js
  src/models/historicalfact.js
  src/models/music.js
  src/models/touristCenter.js
  src/routes/commentRoutes.js
  src/services/AdminServices/ethnicgroup.js
  src/services/AdminServices/historicalFactsService.js
  src/services/AdminServices/musicService.js
  src/services/AdminServices/touristCenterService.js
  src/services/commentServices/index.js
  src/tests/__mock__/commentMockData.js
  src/tests/controllers/users/user-sign-in-test-data.js
  src/tests/index.js
  src/tests/intergration/CommentsRoutes.spec.js
  src/tests/unit/controllers/CountriesController.spec.js
  src/validation/commentValidation.js
Labels: review me

#50 #175557405 Build features to allow an admin activate or deactivate a user
  src/app.js
  src/controllers/admin.js
  src/controllers/commentController.js
  src/controllers/resetPasswordController.js
  src/controllers/user/user.js
  src/database/migrations/20200903160620-create-user.js
  src/database/seeders/20200904133535-User.js
  src/database/seeders/20200914145022-comment.js
  src/middlewares/authenticate.js
  src/models/User.js
  src/models/index.js
  src/routes/adminRoutes/activateUserRoutes.js
  src/routes/commentRoutes.js
  src/routes/resetPasswordRoutes.js
  src/routes/userRoute/userRoutes.js
  src/services/AdminServices/activateUser.js
  src/services/commentServices/index.js
  src/tests/controllers/admin/activateUser.test.js
  src/tests/controllers/admin/deActivateUser.test.js
  src/tests/controllers/users/user-sign-in-test-data.js
  src/tests/controllers/users/user-sign-in-test.js
  src/tests/controllers/users/user-test-data.js
  src/tests/index.js
  src/tests/intergration/CommentsRoutes.spec.js
Labels: review me

#31 #174838693 Implement sign up with Google feature
  .env.sample
  .eslintrc.json
  .github/workflows/node.js.yml
  package.json
  src/UserService/User.js
  src/UserService/jwt.js
  src/app.js
  src/controllers/commentController.js
  src/controllers/food/food.js
  src/controllers/state.js
  src/database/config/google-passport.js
  src/database/migrations/20200903160620-create-user.js
  src/models/User.js
  src/models/state.js
  src/routes/adminRoutes/activateUserRoutes.js
  src/routes/commentRoutes.js
  src/routes/index.js
  src/routes/userRoute/userRoutes.js
  src/services/AdminServices/ethnicgroup.js
  src/services/AdminServices/musicService.js
  src/services/AdminServices/stateService.js
  src/services/AdminServices/touristCenterService.js
  src/services/commentServices/index.js
  src/services/foodServices/food.js
  src/tests/__mock__/commentMockData.js
  src/tests/google-oauth/google-mock-data.js
  src/tests/google-oauth/google-test.spec.js
  src/tests/index.js
  src/tests/intergration/CommentsRoutes.spec.js
  src/tests/models/securityinformation.test.js
  src/utilities/sendgrid.js
Labels: hacktoberfest, review me

#60 Fix: Fix google oauth signin logic
  .env.sample
  src/app.js
  src/database/config/google-passport-signup.js
  src/database/config/googlePassport-signin.js
  src/routes/userRoute/userRoutes.js
Labels: bug, review me
